
name: Tweet Scheduler

on:
  schedule:
    # Run twice a day at random times (this example runs at 9:30 and 17:45)
    - cron: '30 9 * * *'
    - cron: '45 17 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    environment: Xutomation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
      
      - name: Generate Tweet Content
        id: generate
        run: node tweet-generator.js
        
      - name: Verify API Credentials
        run: |
          echo "Checking Twitter API credentials..."
          if [ -z "${{ secrets.TWITTER_API_KEY }}" ] || [ -z "${{ secrets.TWITTER_API_SECRET }}" ] || [ -z "${{ secrets.TWITTER_ACCESS_TOKEN }}" ] || [ -z "${{ secrets.TWITTER_ACCESS_SECRET }}" ]; then
            echo "ERROR: One or more Twitter API credentials are missing. Please check your repository secrets."
            exit 1
          fi
          echo "All API credentials are set."
        
      - name: Post Tweet
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          DEBUG_OAUTH: "true"  # Enable OAuth debug info
        run: |
          echo "Attempting to post tweet with credentials..."
          node post-tweet.js
          
      - name: Log Success
        if: ${{ success() }}
        run: echo "Tweet posted successfully at $(date)"
        
      - name: Log Failure
        if: ${{ failure() }}
        run: |
          echo "Tweet posting failed. Please check the following:"
          echo "1. Verify your Twitter API credentials in repository secrets"
          echo "2. Ensure your Twitter developer app has Read/Write permissions"
          echo "3. Check if your Twitter API access is still active"
