
name: Tweet Scheduler

on:
  schedule:
    # Run twice a day at random times (this example runs at 9:30 and 17:45)
    - cron: '30 9 * * *'
    - cron: '45 17 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
      
      - name: Generate Tweet Content
        id: generate
        run: node tweet-generator.js
        
      - name: Post Tweet
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: node post-tweet.js
        
      - name: Log Success
        run: echo "Tweet posted successfully at $(date)"
